#Whether to modify mob health.
mobScaleHealth = true
#Whether mobs can spawn with armor.
mobArmor = true
#Whether mobs can spawn with effects.
mobEffects = true
#Whether mobs can spawn with weapons. This does not affect vanilla behavior.
mobWeapons = true
#Whether mobs can spawn with enchanted equipment. This does not affect vanilla behavior.
mobEnchantments = true
#Whether to allow mobs to spawn with illegal enchantments.
#
# ON: Mobs can spawn with items can spawn crazily. For example, a chestplate can have sharpness, and a bow can have Infinity and Mending
# OFF: arguably not as fun. you should enable this haha
mobIllegalEnchantments = false
#Chance for mob to randomly spawn slightly weaker
#
#0: no chance for mob to be weaker.
#1: 100% chance for mob to be weaker.
#Range: 0.0 ~ 1.0
mobRandomlyWeakerChance = 0.4
#Ranged amount % weaker when mob spawns weaker
#
#0: 0% weaker than normal.
#1: 100% weaker than normal. Basically no scaling.
#Range: 0.0 ~ 1.0
mobRandomlyWeakerAmount = 0.2
#Whether to always level up on boss kills.
mobBossAlwaysLevelUp = true
#Maximum level a player can attain.
#Range: > 5
playerLevelCap = 35
#Range of levels that a player can gain/lose. This pairs in how quickly it is to reach the level cap
#Example: range of 10 roughly nets 3 - 5 levels on leveling up through normal gameplay
#Range: > 2
playerScaleRange = 5
#Percent of current level amount of levels to lose on death.
#
#0: no levels lost
#1: lose all levels
#Range: 0.0 ~ 1.0
playerLoseLevelsDeath = 0.2
#Maximum amount of levels to lose on death. This effectively clamps the Player % lose levels death after its calculation.
#
#0: no levels lost
#Integer.MAX_VALUE: unclamped
#Range: > 0
playerLoseLevelsDeathCap = 30
#Multiplier of towards the losing of levels. Often times the base losing level may be small, so a multiplier may help in decreasing larger levels.
#
#0: lose no levels, will make gameplay miserable as mobs will scale infinitely no matter what
#1: lose normal amount, limited to player scaling range
#2: twice as much etc
#Range: 0.0 ~ 2.147483647E9
playerLoseLevelsMultiplier = 1.1
#Maximum amount of levels to lose when scaling naturally.
#Range: > 0
playerLoseLevelsCap = 35
#Minimum % mob level to count towards scaling upon kill. This helps to mitigate farming low level thus weaker mobs to scale faster.
#
# For example 0.3: for a mob to count towards scaling, its level must be at least greater than or within the player's current level - 30% the player's level.
#Range: 0.0 ~ 1.0
playerVsMobLevel = 0.3
#Maximum amount of level difference that a mob can be below the player to count towards scaling upon kill.
#
# For example 50: for a mob to count towards scaling, its level must be at least greater than or within the player's current level - 50.
# 0: must be exact level
# 100: mob can be 100 levels below player level to count
# Integer.MAX_VALUE: unclamped, mob can be any level
#Range: > 0
playerVsMobLevelCap = 50
#Clamps the strength of gaining/losing levels upon kills.
#
#Lower: more sensitive
#Higher: less sensitive
#Range: 1.0 ~ 5.0
playerZClamp = 2.0
#Shifts the central point of the scaling curve, either in favor of gaining/losing levels.
#
#0: no bias, equal chance to gain/lose levels
#Higher: more likely to level up, even with lower performance
#Range: 0.0 ~ 2.0
playerZBias = 0.4
#Number of recent datapoints to account for in determining the average scaling calculation.
#
#Lower = abrupt changes in scaling
#Higher = smoother changes in scaling
#Range: 5 ~ 50
playerEWMA = 7
#Sets the aggressiveness of scaling as player performance deviates. 
#
#0.1: react strongly
#2: stable leveling, only detects massive outliers
#Range: 0.1 ~ 2.0
playerZCurveExponent = 0.85
#Prevents scaling overreaction to outliers if recent performance has been consistent. 
#
#0: sensitive abrupt scaling
#1: slow scaling from changes, may feel sluggish
#Range: 0.0 ~ 1.0
playerVariance = 0.25
#Debug text into console
debugText = false

