
["Flavor Text"]
	#Enable Flavor Text tooltips.
	"Flavor Text" = false

["Farming & Foraging XP"]
	#Global multiplier applied to ALL farming & foraging XP.
	#Range: 0.0 ~ 100.0
	"XP Global Multiplier" = 1.0

["XP Source Toggles"]
	#Enable XP from crop harvesting, this includes knife-breaking crops for secondary drops.
	"Crop Harvest XP" = true
	#Enable XP from knife-breaking wild crops and for right-click harvests like Bountiful Leaves, etc.
	"Foraging XP" = true
	#Enable XP from shearing wool or feathers from sheep and chickens.
	"Animal Shear XP" = true
	#Enable XP from collecting from a full Tapper.
	"Tapper XP" = true
	#Enable XP from harvesting Honey or shearing Honeycomb
	"Beehive XP" = true
	#Enable XP from milking cows.
	"Milking XP" = true

