#.
#Config version check, values below 0 will disable config version checker
#Range: > -2147483648
configVersion = 1

#.
#Things related to kinetic and electrokinetic devices
[kinetics]
	#.
	#.
	#Cooling multiplier applied to devices in the air stream (multiplied by rotational speed)
	#Range: 0.0 ~ 3.4028234663852886E38
	encasedFanCooling = 0.009999999776482582
	#.
	#Controls the torque force calculated from stress impact of machines (used by generators and motors)
	#Range: 0.0 ~ 3.4028234663852886E38
	torqueForStress = 15.0
	#.
	#How much lightning rod linear velocity is needed to reach the maximum lightning attractor firing rate
	#Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorSpeedFactor = 0.05000000074505806
	#.
	#How many sail blocks are needed to reach the maximum lightning attractor firing rate
	#Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorSailFactor = 0.125
	#.
	#How often can the lightning attractor fire
	#Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorMaxFrequency = 0.05000000074505806

	#.
	#Rotor control factors
	[kinetics.generatorControl]
		#.
		#.
		#Factor to scale the Proportional factorof the Rotor's force calculation
		#Range: 0.0 ~ 3.4028234663852886E38
		rotorKp = 0.8500000238418579
		#.
		#Factor to scale the Differential factor of the Rotor's force calculation
		#Range: 0.0 ~ 3.4028234663852886E38
		rotorKd = 0.0020000000949949026
		#.
		#Maximum rotation speed of a rotor
		#Range: > 0
		rotorRPMMax = 256
		#.
		#Maximum length of a rotor assembly
		#Range: > 3
		rotorAssemblyMaxSize = 8
		#.
		#Force of friction applied for each segment of the rotor assembly
		#Range: 0.0 ~ 3.4028234663852886E38
		rotorSegmentFriction = 0.25
		#.
		#Range: 0.0 ~ 3.4028234663852886E38
		generatorRotorInertia = 0.5
		#.
		#Range: 0.0 ~ 3.4028234663852886E38
		generatorInductionRotorInertia = 0.5
		#.
		#Range: 0.0 ~ 3.4028234663852886E38
		generatorCommutatorInertia = 0.10000000149011612
		#.
		#Range: 0.0 ~ 3.4028234663852886E38
		generatorClutchInertia = 0.10000000149011612
		#.
		#Controls the conversion rate between RPM and voltage generated by windings
		#Range: 0.10000000149011612 ~ 3.4028234663852886E38
		windingCoilConstant = 5.0
		#.
		#Current required for maximum field strength of the generator's field windings
		#Range: 0.0 ~ 3.4028234663852886E38
		fieldSaturationCurrent = 2.0

	[kinetics.stressValues]

		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v3]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v3.impact]
				generator_clutch = 32.0
				hv_breaker = 2.0
				generator_induction_rotor = 32.0
				hv_switch = 2.0
				rheostat = 0.0
				generator_vertical_commutator = 8.0
				plotter = 2.0
				punch_card_reader = 2.0
				variac = 0.0
				generator_commutator = 8.0

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v3.capacity]
				servo = 32.0
				constant_speed_motor = 64.0
				electric_motor = 64.0

#.
#Recipe configuration values
[recipes]
	#.
	#.
	#Chance for lightning strike to turn a single iron ingot into a magnet
	#Range: 0.0 ~ 1.0
	lightningMagnetizationChance = 0.05000000074505806

#.
#All things related to purely electrical devices
[electricity]
	#.
	#.
	#Controls the behaviour of overheated devices. If false, instead of exploding, they break without dropping items.
	explosiveDeconstruction = true
	#.
	#Controls the overheat mechanic. Devices which are overheated, break.
	overheating = true
	#.
	#Controls the overheat mechanic for wires. Wires will burn if they overheat.
	wireOverheating = true
	#.
	#Multiplier of the base fan bulk processing time applied to items processed with the heating coil (lower value means faster processing)
	#Range: 0.0 ~ 3.4028234663852886E38
	heaterFanProcessingSpeedMultiplier = 0.75
	#.
	#Radius of the area affected by growth lamp effect
	#Range: > 1
	growthLampRadius = 2
	#.
	#Chance value for the growth lamp to tick a random block in its area (lower value = higher chance), this value is divided by lamp's power level
	#Range: > 0
	growthLampChance = 50
	#.
	#Conversion rate of volts to Forge Energy
	#Range: 0.0 ~ 3.4028234663852886E38
	forgeEnergyPerVolt = 2.0
	#.
	#Conversion rate of watts to Forge Energy
	#Range: 0.0 ~ 3.4028234663852886E38
	forgeEnergyPerWatt = 10.0
	#.
	#Maximum power generated by a device connector when it is connected to a 'Create: The Factory Must Grow' electrical network
	#Range: > 0
	TFMGConnectorPower = 10000
	#.
	#Forge Energy used by Electro-Zapper per shot
	#Range: > 1
	electroZapperFePerShot = 100
	#.
	#Portable Battery Forge Energy capacity before enchants
	#Range: > 1
	portableBatteryBaseCapacity = 10000
	#.
	#Portable Battery Forge Energy capacity increase per level of Capacity enchant
	#Range: > 1
	portableBatteryEnchantCapacity = 10000
	#.
	#Initial charge of the acid battery
	#Range: 0.0 ~ 1.0
	acidBatteryInitialCharge = 0.8999999761581421
	#.
	#Multiplies the mutual inductance of transformers to get a resistance. Bigger values make transformers use less electricity.
	#Range: 1.0 ~ 3.4028234663852886E38
	transformerMutualInductanceMultiplier = 10.0
	#.
	#Percent of the turn-on current required for on state to be kept by relays and conductors
	#Range: 0.009999999776482582 ~ 0.9900000095367432
	holdingCurrentPercent = 0.8999999761581421
	#.
	#Minimum blocks needed for a grounding rod to work
	#Range: > 0
	groundingMinimumBlocks = 10
	#.
	#Maximum conductive blocks needed for a grounding rod to reach its lowest resistance
	#Range: > 0
	groundingMaximumBlocks = 64
	#.
	#Highest resistance of the grounding rod
	#Range: 0.0010000000474974513 ~ 3.4028234663852886E38
	groundingHighestResistance = 5000.0
	#.
	#Lowest resistance of the grounding rod
	#Range: 0.0010000000474974513 ~ 3.4028234663852886E38
	groundingLowestResistance = 1.0
	#.
	#Maximum block height of the carbon pile structure
	#Range: > 1
	carbonPileMaxHeight = 5
	#.
	#Carbon pile "gain", controls how much the coil current affects the resistance
	#Range: 0.0 ~ 3.4028234663852886E38
	carbonPileGain = 10.0
	#.
	#Max multimeter distance
	#Range: 1.0 ~ 3.4028234663852886E38
	multimeterDistance = 5.0
	#.
	#Max multimeter voltage
	#Range: 1.0 ~ 3.4028234663852886E38
	multimeterVoltage = 500.0
	#.
	#Max multimeter current
	#Range: 1.0 ~ 3.4028234663852886E38
	multimeterCurrent = 50.0
	#.
	#Al parameter of small transformer core (affects resistance per turn)
	#Range: 0.0 ~ 3.4028234663852886E38
	smallCoreAl = 1.5
	#.
	#K parameter of small transformer core (affects stray resistance)
	#Range: 0.0 ~ 1.0
	smallCoreK = 0.9998999834060669
	#.
	#Al parameter of medium transformer core (affects resistance per turn)
	#Range: 0.0 ~ 3.4028234663852886E38
	mediumCoreAl = 10.0
	#.
	#K parameter of medium transformer core (affects stray resistance)
	#Range: 0.0 ~ 1.0
	mediumCoreK = 0.9999899864196777

	#.
	#Things related to how the simulation is handled (probably shouldn't be altered unless you know what you are doing)
	[electricity.solver]
		#.
		#.
		#Threshold resistance for a transmission line to be able to split the grid into island networks. Lines with resistance above this value have a propagation delay of roughly 1 tick, and can improve performance by simulating small segments of the grid separately.
		#Range: 0.0 ~ 3.4028234663852886E38
		transmissionLineThreshold = 0.20000000298023224
		#.
		#Experimental! Allows transmission lines to split large grid into smaller networks. This option should improve performance for large grids but it will result in transmission lines having a propagation delay and capacitance.
		splittingTransmissionLines = false
		#.
		#Allows transformers to split the grid. This option should improve performance but it will result in transformers having some capacitance and delay.
		splittingsTransformers = false
		#.
		#Maximum solver iterations for networks without dynamic residuals
		#Range: > -2147483648
		solverSimpleMaxIterations = 200
		#.
		#Maximum solver iterations for networks with dynamic residuals
		#Range: > -2147483648
		solverComplexMaxIterations = 200
		#.
		#Absolute stopping criterion
		#Range: 0.0 ~ 3.4028234663852886E38
		solverAbsolutePrecision = 1.0000000116860974E-7
		#.
		#Relative stopping criterion
		#Range: 0.0 ~ 3.4028234663852886E38
		solverRelativePrecision = 1.0000000036274937E-15
		#.
		#Minimum accepted precision
		#Range: 0.0 ~ 3.4028234663852886E38
		solverAbsoluteMinimumPrecision = 9.999999974752427E-7
		#.
		#Experimental! This option enables all electrical networks to tick multiple times per world tick. This allows for better simulation precision when reactive components are involved but can have a significant impact on performance.
		#Range: > 1
		multiTicks = 1
		#.
		#Solver MNA backend. The native backend can provide platform-specific acceleration which usually improves performance, however it isn't portable and needs a special binary which might not be available for all platforms. Java backend is portable and always available as fallback.
		#Allowed Values: JAVA, NATIVE
		solverBackend = "NATIVE"

	#.
	#Resistance values for all devices
	[electricity.resistance-v3]

		#.
		#.
		#[in Ohms]
		#Configure the individual resistances of electrical blocks
		[electricity.resistance-v3.resistance]
			portable_battery = 25.0
			heating_coil = 25.0
			current_gauge = 0.05000000074505806
			lv_switch = 0.15
			carbon_pile = 20.0
			electric_motor = 25.6
			electromagnet = 15.0
			fuse_holder = 0.2
			mv_switch = 0.05
			carbon_pile_coil = 50.0
			hv_breaker = 0.1
			generator_induction_rotor = 0.5
			winding = 7.5
			lv_button = 0.15
			hv_switch = 0.1
			electric_fan = 20.0
			punch_card_reader = 1.0
			basin_heater = 10.0
			constant_speed_motor = 25.6
			power_gauge = 0.05000000074505806
			alarm_bell = 20.0

			[electricity.resistance-v3.resistance.crt]
				coils = 40.0
				heater = 12.0

			[electricity.resistance-v3.resistance.servo]
				idle = 64.0
				on = 12.8

			[electricity.resistance-v3.resistance.contactor]
				switch = 0.05
				coil = 12.0

	#.
	#Thermal properties for all devices
	[electricity.thermal-v1]

		#.
		#.
		#Configures the amount of energy needed to raise the temperature of the device (this allows for higher temporary loads)
		[electricity.thermal-v1.mass]
			portable_battery = 1.0
			hv_breaker = 2.0
			winding = 1.5
			contactor = 2.0
			hv_switch = 2.0
			lv_button = 0.5
			heating_coil = 1.0
			current_gauge = 2.0
			rheostat = 4.0
			punch_card_reader = 0.20000000298023224
			battery = 1.5
			power_resistor = 2.0
			lv_switch = 0.5
			carbon_pile = 2.0
			alarm_bell = 1.5
			variac = 4.0
			power_gauge = 2.0
			electromagnet = 4.0
			transformer_medium = 16.0
			transformer_small = 4.0
			mv_switch = 1.0
			carbon_pile_coil = 2.0
			crt = 3.0

		#.
		#[in Watts]
		#Configures the maximum power dissipated by the device
		[electricity.thermal-v1.power]
			portable_battery = 100.0
			hv_breaker = 102.4
			winding = 200.0
			contactor = 252.8
			hv_switch = 153.6
			lv_button = 38.4
			heating_coil = 60.0
			current_gauge = 35.0
			rheostat = 1000.0
			punch_card_reader = 10.0
			battery = 100.0
			power_resistor = 1000.0
			lv_switch = 38.4
			carbon_pile = 1000.0
			alarm_bell = 50.0
			variac = 1000.0
			power_gauge = 35.0
			electromagnet = 1500.0
			transformer_medium = 4000.0
			transformer_small = 1000.0
			mv_switch = 51.2
			carbon_pile_coil = 100.0
			crt = 100.0

	#.
	#Configuration of server-side wire properties
	[electricity.wires-v1]

		#.
		#.
		[electricity.wires-v1.wire]

			[electricity.wires-v1.wire.golden_wire]
				resistance = 0.003000000026077032
				thermal-mass = 0.800000011920929
				max-length = 8.0
				max-current = 160.0

			[electricity.wires-v1.wire.copper_cord]
				resistance = 0.001500000013038516
				max-length = 8.0
				thermal-mass = 2.0
				max-current = 60.0

			[electricity.wires-v1.wire.insulated_copper_wire]
				thermal-mass = 1.2000000476837158
				max-length = 16.0
				max-current = 70.0
				resistance = 0.001500000013038516

			[electricity.wires-v1.wire.string_light_cord]
				max-current = 60.0
				thermal-mass = 2.0
				max-length = 8.0
				resistance = 0.001500000013038516

			[electricity.wires-v1.wire.wire]
				resistance = 0.001500000013038516
				max-length = 16.0
				thermal-mass = 1.0
				max-current = 80.0

			[electricity.wires-v1.wire.iron_wire]
				max-length = 32.0
				thermal-mass = 2.0
				resistance = 0.004999999888241291
				max-current = 160.0

