
[Thruster]
	#Thrust is multiplied by that.
	"Thrust multiplier" = 1.0
	#Fuel consumption is multiplied by that.
	"Fuel consumption" = 1.0
	#Thrusters stop accelerating ships upon reaching this speed. Defined in blocks per second.
	#Range: 10 ~ 200
	"Thruster speed limit" = 100
	#Thruster tick rate. Lower values make fluid consumption a little more precise.
	#Range: 1 ~ 100
	"Thruster tick rate" = 10
	#If true - thrusters will damage entities. May have negative effect on performance if a lot of thrusters are used.
	"Thrusters damage entities" = true

["Creative Thruster"]
	#Thrust is multiplied by that.
	"Creative thrust multiplier" = 1.0

["Optical sensors"]
	#How many ticks between casting a ray. Lower values are more precise, but can have negative effect on performance.
	#Range: 1 ~ 100
	"Optical sensor tick rate" = 2
	#Length of the raycast ray.
	#Range: 4 ~ 32
	"Inline optical sensor max raycast distance" = 16
	#Length of the raycast ray. Very high values may degrade performance. Change with caution!
	#Range: 8 ~ 64
	"Optical sensor max raycast distance" = 32

["Redstone magnet"]
	#Magnet power is multiplied by that.
	"Power multiplier" = 1.0
	#Torque induced by offset of the force-applying magnet from COM. Value of 1.0 is realistic but does not allow for statically stable contraptions. Modify this value only if you know what you are doing!
	"Force-induced torque multiplier" = 1.0

["Physics assembler"]
	#Maximum distance between region selected with assembly gauge and physics assembler block.
	"Max distance to region" = 3
	#Maximum size of the region that can be selected with assembly gauge.
	"Max size" = 128

[Wing]
	#Wing's lift force is multiplied by this number.
	"Base lift" = 150.0
	#Wing's drag force is multiplied by this number.
	"Base drag" = 150.0

["Hot air balloons"]
	#Balloon's buoyant force is multiplied by that.
	"Balloon force multiplier" = 375.0
	#The higher this values is - the more hot air leaks out naturally.
	"Surface leak factor" = 0.01
	#The higher this values is - the more hot air leaks out of holes in balloon.
	"Hole leak factor" = 0.25
	#This value controls how many holes need to be made on one balloon layer to remove it from balloon's volume.
	"Hole layer removal threshold" = 0.5

	["Hot air balloons"."Hot air burner"]
		#The amount of hot air generated by hot air burner is multiplied by that value.
		"Hot air burner output multiplier" = 1.0

	["Hot air balloons"."Hot air pump"]
		#Base amount of hot air injected by a Hot Air Pump running at maximum speed at heat level of one (solid burner).
		"Base injection amount" = 6.0

	["Hot air balloons".Drag]
		#Angular damping torque is multiplied by this. Higher values slow down rotation of ships with balloons more.
		"Angular damping" = 1.2
		#Vertical angular alignment torque is multiplied by this.
		"Vertical angular alignment" = 10.0
		#Vertical linear drag.
		"Vertical linear drag" = 100.0
		#Horizontal linear drag.
		"Horizontal linear drag" = 80.0

[Propeller]
	#Propellers stop accelerating ships upon reaching this speed. Defined in blocks per second
	#Range: 10.0 ~ 100.0
	"Max speed" = 40.0
	#Propeller force and torque are multiplied by this number
	#Range: 0.01 ~ 100.0
	"Power multiplier" = 6.0
	#Propeller force when it is underwater is multiplied by this number
	#Range: 0.01 ~ 100.0
	"Underwater power multiplier" = 1.0
	#Propeller torque is multiplied by this number
	#Range: 0.0 ~ 100.0
	"Torque effect multiplier" = 1.0

["Stirling Engine"]
	#Change this value to modify the amount of stress units produced by stirling engine. Value of 16 corresponds to 4096 SU.
	#Range: 1.0 ~ 64.0
	"Generated stress units" = 16.0

["Tilt Adapter"]
	#Angle range of the tilt adapter. Better leave it close to 30.
	#Range: 10.0 ~ 60.0
	"Angle range" = 30.0

[Atmosphere]
	#Height factor of the atmosphere. Increase this value if balloons are flying too low.
	"Height factor" = 1.0
	#Magnitude of the perlin noise of the atmosphere. Higher values result in higher turulence and less control over the altitude.
	"Noise magnitude" = 1.0
	#Speed of atmospheric perlin noise change. Higher values make atmosphere (and therefore balloons and propellers) more unstable.
	"Noise time factor" = 1.0

[Burners]
	#If true - both solid and liquid burners can provide heat to heated mixers allowing for pre-nether brass.
	"Burners power heated mixers" = true

["Stress impacts"]
	hot_air_pump = 8.0

